### ISSUE TITLE
Dynamo 2.17 compatibility with Topology.Geometry node

### ISSUE THREAD

**Issue by chartreuseUNICORN** [wassimj/Topologic#43]
Not sure if the Dynamo package is currently supported, but i found some unexpected behavior with geometry conversion in Dynamo 2.17.

Wires created from Circles, or wires derived from Circles (arcs), are converted back as NurbsCurves with a high number of knots.  In 2.13 and previous, Topology.Geometry node would convert back to Dynamo as Circles, or Arcs.  

ex:
![image](https://github.com/wassimj/Topologic/assets/24413366/dc84cd5d-7f6a-4d24-b734-acb0080085f4)

I'm imprinting these curves into the surface which should create 4 faces.  in 2.13, the resulting edges associated with the circle get converted as Arcs, but in 2.17 they are converted as NurbsCurves with ~130 knots which fail to convert from Dynamo Curves to Revit Curves

edit: i'm still trying to determine an exact cause of the behavior.  If you get the geometry from the Wires or Edges, they are NurbsCurves in both 2.13 and 2.17.  If you get the surface geometry from the faces, and then get the polycurves from the surface, then they're constructed as Arcs and Circles in 2.13, and NurbsCurves in 2.17.

It would be nice to keep using topologic because the Imprint function is exactly what i'm looking for.

**Comment by wassimj** [comment]
The code for TopologicDynsmo has not changed in several years. It tries to create the most compatible geometry version of the topology. So something has changed in the Dynamo code that is forcing topologic to revert to a NURBS curve with many knots instead of arcs. Sadly, TopologicDynamo is not being developed further at this point. And topologicpy ignores NURBS and focuses on planar geometry.
